<?php

namespace DoctrineProxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Probe extends \Entities\Probe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Probe' . "\0" . 'atlas_id', '' . "\0" . 'Entities\\Probe' . "\0" . 'v4_enabled', '' . "\0" . 'Entities\\Probe' . "\0" . 'v6_enabled', '' . "\0" . 'Entities\\Probe' . "\0" . 'id', '' . "\0" . 'Entities\\Probe' . "\0" . 'network', '' . "\0" . 'Entities\\Probe' . "\0" . 'v4_address', '' . "\0" . 'Entities\\Probe' . "\0" . 'v6_address'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Probe' . "\0" . 'atlas_id', '' . "\0" . 'Entities\\Probe' . "\0" . 'v4_enabled', '' . "\0" . 'Entities\\Probe' . "\0" . 'v6_enabled', '' . "\0" . 'Entities\\Probe' . "\0" . 'id', '' . "\0" . 'Entities\\Probe' . "\0" . 'network', '' . "\0" . 'Entities\\Probe' . "\0" . 'v4_address', '' . "\0" . 'Entities\\Probe' . "\0" . 'v6_address'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Probe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAtlasId($atlasId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasId', [$atlasId]);

        return parent::setAtlasId($atlasId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasId', []);

        return parent::getAtlasId();
    }

    /**
     * {@inheritDoc}
     */
    public function setV4Enabled($v4Enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV4Enabled', [$v4Enabled]);

        return parent::setV4Enabled($v4Enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getV4Enabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV4Enabled', []);

        return parent::getV4Enabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setV6Enabled($v6Enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV6Enabled', [$v6Enabled]);

        return parent::setV6Enabled($v6Enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getV6Enabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV6Enabled', []);

        return parent::getV6Enabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetwork(\Entities\Network $network = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetwork', [$network]);

        return parent::setNetwork($network);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetwork', []);

        return parent::getNetwork();
    }

    /**
     * {@inheritDoc}
     */
    public function setV4Address($v4Address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV4Address', [$v4Address]);

        return parent::setV4Address($v4Address);
    }

    /**
     * {@inheritDoc}
     */
    public function getV4Address()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV4Address', []);

        return parent::getV4Address();
    }

    /**
     * {@inheritDoc}
     */
    public function setV6Address($v6Address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setV6Address', [$v6Address]);

        return parent::setV6Address($v6Address);
    }

    /**
     * {@inheritDoc}
     */
    public function getV6Address()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getV6Address', []);

        return parent::getV6Address();
    }

}
