<?php

namespace DoctrineProxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Measurement extends \Entities\Measurement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_start', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_stop', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_start', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_stop', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_data', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_data', '' . "\0" . 'Entities\\Measurement' . "\0" . 'id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'result', '' . "\0" . 'Entities\\Measurement' . "\0" . 'request', '' . "\0" . 'Entities\\Measurement' . "\0" . 'destinationNetwork'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_start', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_stop', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_start', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_stop', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_out_data', '' . "\0" . 'Entities\\Measurement' . "\0" . 'atlas_in_data', '' . "\0" . 'Entities\\Measurement' . "\0" . 'id', '' . "\0" . 'Entities\\Measurement' . "\0" . 'result', '' . "\0" . 'Entities\\Measurement' . "\0" . 'request', '' . "\0" . 'Entities\\Measurement' . "\0" . 'destinationNetwork'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Measurement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAtlasOutId($atlasOutId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasOutId', [$atlasOutId]);

        return parent::setAtlasOutId($atlasOutId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasOutId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasOutId', []);

        return parent::getAtlasOutId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasInId($atlasInId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasInId', [$atlasInId]);

        return parent::setAtlasInId($atlasInId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasInId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasInId', []);

        return parent::getAtlasInId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasOutStart($atlasOutStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasOutStart', [$atlasOutStart]);

        return parent::setAtlasOutStart($atlasOutStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasOutStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasOutStart', []);

        return parent::getAtlasOutStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasOutStop($atlasOutStop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasOutStop', [$atlasOutStop]);

        return parent::setAtlasOutStop($atlasOutStop);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasOutStop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasOutStop', []);

        return parent::getAtlasOutStop();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasInStart($atlasInStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasInStart', [$atlasInStart]);

        return parent::setAtlasInStart($atlasInStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasInStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasInStart', []);

        return parent::getAtlasInStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasInStop($atlasInStop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasInStop', [$atlasInStop]);

        return parent::setAtlasInStop($atlasInStop);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasInStop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasInStop', []);

        return parent::getAtlasInStop();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasOutData($atlasOutData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasOutData', [$atlasOutData]);

        return parent::setAtlasOutData($atlasOutData);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasOutData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasOutData', []);

        return parent::getAtlasOutData();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtlasInData($atlasInData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtlasInData', [$atlasInData]);

        return parent::setAtlasInData($atlasInData);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtlasInData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtlasInData', []);

        return parent::getAtlasInData();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResult(\Entities\Result $result = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResult', [$result]);

        return parent::setResult($result);
    }

    /**
     * {@inheritDoc}
     */
    public function getResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', []);

        return parent::getResult();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequest(\Entities\Request $request = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequest', [$request]);

        return parent::setRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequest', []);

        return parent::getRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinationNetwork(\Entities\Network $destinationNetwork = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinationNetwork', [$destinationNetwork]);

        return parent::setDestinationNetwork($destinationNetwork);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinationNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationNetwork', []);

        return parent::getDestinationNetwork();
    }

}
