<?php

namespace DoctrineProxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Request extends \Entities\Request implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Request' . "\0" . 'nonce', '' . "\0" . 'Entities\\Request' . "\0" . 'protocol', '' . "\0" . 'Entities\\Request' . "\0" . 'created', '' . "\0" . 'Entities\\Request' . "\0" . 'started', '' . "\0" . 'Entities\\Request' . "\0" . 'completed', '' . "\0" . 'Entities\\Request' . "\0" . 'id', '' . "\0" . 'Entities\\Request' . "\0" . 'network', '' . "\0" . 'Entities\\Request' . "\0" . 'measurements', '' . "\0" . 'Entities\\Request' . "\0" . 'IXP'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Request' . "\0" . 'nonce', '' . "\0" . 'Entities\\Request' . "\0" . 'protocol', '' . "\0" . 'Entities\\Request' . "\0" . 'created', '' . "\0" . 'Entities\\Request' . "\0" . 'started', '' . "\0" . 'Entities\\Request' . "\0" . 'completed', '' . "\0" . 'Entities\\Request' . "\0" . 'id', '' . "\0" . 'Entities\\Request' . "\0" . 'network', '' . "\0" . 'Entities\\Request' . "\0" . 'measurements', '' . "\0" . 'Entities\\Request' . "\0" . 'IXP'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Request $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNonce($nonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNonce', [$nonce]);

        return parent::setNonce($nonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getNonce()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNonce', []);

        return parent::getNonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtocol($protocol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocol', [$protocol]);

        return parent::setProtocol($protocol);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocol', []);

        return parent::getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setStarted($started)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStarted', [$started]);

        return parent::setStarted($started);
    }

    /**
     * {@inheritDoc}
     */
    public function getStarted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStarted', []);

        return parent::getStarted();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompleted($completed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompleted', [$completed]);

        return parent::setCompleted($completed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleted', []);

        return parent::getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetwork(\Entities\Network $network = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetwork', [$network]);

        return parent::setNetwork($network);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetwork', []);

        return parent::getNetwork();
    }

    /**
     * {@inheritDoc}
     */
    public function addMeasurement(\Entities\Measurement $measurement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMeasurement', [$measurement]);

        return parent::addMeasurement($measurement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMeasurement(\Entities\Measurement $measurement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMeasurement', [$measurement]);

        return parent::removeMeasurement($measurement);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeasurements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeasurements', []);

        return parent::getMeasurements();
    }

    /**
     * {@inheritDoc}
     */
    public function setIXP(\Entities\IXP $iXP = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIXP', [$iXP]);

        return parent::setIXP($iXP);
    }

    /**
     * {@inheritDoc}
     */
    public function getIXP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIXP', []);

        return parent::getIXP();
    }

}
